# Generated by Django 3.1.1 on 2020-11-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20201105_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'Url', 'verbose_name_plural': 'Urls'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
